spring:
    application:
        name: GRIB-SCHEDULING
    profiles:
        group:
            local: local
            dev: dev
---
server:
    port: 8081
spring:
    config:
        activate:
            on-profile: local
    datasource:
        db1:
            jdbc-url: jdbc:mysql://localhost:3306/grib_scheduling
            username: root
            password: grib12#$
            driver-class-name: com.mysql.cj.jdbc.Driver
        db2:
            jdbc-url: jdbc:mysql://localhost:3306/db_oauth
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: root
            password: grib12#$
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect
    client:
        # secret: $2a$10$a4RlLs39Mba7XhD9M5suSeBcG5iMbXh5XzfNREnGL5fmQEItbya3m
        secret: $2a$10$8.Q.gxUmGJP36W.uzANIsen8h.gmWJnfQAvHRH6BAIZ7pdYwM/hxG
    kafka:
        replication-factor: 1
        broker-server: "http://huring.grib-iot.com:9513"
---
server:
    port: 9997
    ssl:
        enabled: true
        key-store: classpath:ssl/_wildcard_.grib-iot.com_202504073F0DF.jks
        key-store-password: 2zp9y22f
        key-store-type: JKS
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        db1:
            jdbc-url: jdbc:mysql://192.168.0.240:3306/scheduling_dev
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: grib
            password: grib12!@
        db2:
            jdbc-url: jdbc:mysql://192.168.0.240:3306/oauth_dev
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: grib
            password: grib12!@
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: none
        show-sql: true
    client:
        secret: $2a$10$8.Q.gxUmGJP36W.uzANIsen8h.gmWJnfQAvHRH6BAIZ7pdYwM/hxG
    kafka:
        replication-factor: 1
        broker-server: "http://192.168.0.240:29092"
